# Generated by Django 5.0.6 on 2024-06-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('summary', models.TextField(max_length=2000)),
                ('school', models.CharField(max_length=200)),
                ('school_gpa', models.FloatField(blank=True, null=True)),
                ('school_joined_year', models.CharField(blank=True, max_length=5, null=True)),
                ('school_left_year', models.CharField(blank=True, max_length=5, null=True)),
                ('college', models.CharField(max_length=200)),
                ('college_gpa', models.FloatField(blank=True, null=True)),
                ('stream', models.CharField(choices=[('Science', 'Science'), ('Management', 'Management'), ('Humanities', 'Humanities')], max_length=20)),
                ('college_joined_year', models.CharField(blank=True, max_length=5, null=True)),
                ('college_left_year', models.CharField(blank=True, max_length=5, null=True)),
                ('university', models.CharField(max_length=200)),
                ('university_gpa', models.FloatField(blank=True, null=True)),
                ('university_faculty', models.CharField(max_length=200)),
                ('university_joined_year', models.CharField(blank=True, max_length=5, null=True)),
                ('university_left_year', models.CharField(blank=True, max_length=5, null=True)),
                ('project', models.CharField(blank=True, max_length=100, null=True)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('technical_skills', models.CharField(blank=True, max_length=2000, null=True)),
                ('nontechnical_skills', models.CharField(blank=True, max_length=2000, null=True)),
                ('language', models.CharField(blank=True, max_length=2000, null=True)),
                ('reference_name', models.CharField(blank=True, max_length=200, null=True)),
                ('reference_position', models.CharField(blank=True, max_length=200, null=True)),
                ('reference_organization', models.CharField(blank=True, max_length=200, null=True)),
                ('reference_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('reference_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
