# Generated by Django 5.0.6 on 2024-06-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_alter_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='project_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
